# Generated by Django 4.0.6 on 2022-08-13 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته')),
                ('image', models.ImageField(upload_to='images/category', verbose_name='عکس')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='عنوان url')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='قیمت')),
                ('discount', models.CharField(max_length=255, verbose_name='تخفیف')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='عنوان url')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال,غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='به روز رسانی شده در تاریخ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول ها',
                'ordering': ('created_at',),
            },
        ),
    ]
